### PR TITLE
Separating the helper logic from the main logic

### PR DESCRIPTION
**Pull request by koleshjr**
Okay just a question, do you think separating the helper functions -the welcome and the samurai one from the main logic would enhance readability, and improve on the code structure? ,  now the main will just call the helper functions , other thun implementing the whole logic inside the main function?

### CODE REVIEW

**Comment by CyndieKamau** [comment]
Well makes sense. I did include the helper functions inside the main logic. In other projects, I'd separate them.

Oh and also, I can't seem to get rid of the target folder even after adding a .gitignore file. What am I missing?

**Review by CyndieKamau — APPROVED** [review]
Yeah this will improve readability.

**Comment by koleshjr** [comment]
so  since you have multiple rust projects in this repo:
in the gitignore file add /target/
then since you have some target folders already run the below lines:
git rm -r --cached target/
git commit -am"removed target folders from repo history bla bla bla"
git push origin <branch>

**Comment by CyndieKamau** [comment]
Nice thanks. Lemme do that

**Pull request merged**
